server:
  port: 7900
spring:
  application:
    name: microservice-nacos-order  # 指定应用名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # Nacos 服务器地址
        namespace: public  # 命名空间，默认为 public
        group: DEFAULT_GROUP  # 分组，默认为 DEFAULT_GROUP
        ephemeral: true  # 是否为临时实例