server:
  port: 8000
spring:
  application:
    name: microservice-nacos-user  # 指定应用名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # Nacos 服务器地址
        namespace: public  # 命名空间，默认为 public
        group: DEFAULT_GROUP  # 分组，默认为 DEFAULT_GROUP
        ephemeral: true  # 是否为临时实例
    sentinel:
      transport:
        # Sentinel Dashboard 地址（需要单独部署）
        dashboard: localhost:8080
        # 服务与控制台交互的端口
        port: 8719
      # 开启对 Spring MVC 端点的保护
      filter:
        enabled: true
      # 取消控制台懒加载
      eager: true